<?php

use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;
use Drupal\Core\Entity;

function publish_entity_presave(\Drupal\Core\Entity\EntityInterface $entity) {
  // call to trigger content push.
  \Drupal::service('publish.utility')->publish_presave($entity);
}

function insert_mapping($entity, $response) {
  // if (is_object($response)) {
  //   switch ($entity->getEntityTypeId()) {
  //     case 'taxonomy_term';
  //       $entity_id = $response->tid[0]->value;
  //     break;
  //     case 'node';
  //       $entity_id = $response->nid[0]->value;
  //     break;
  //     case 'user';
  //       $entity_id = $response->uid[0]->value;
  //     break;
  //   }
  //   $connection = Database::getConnection();
  //   $connection->insert('publish_to_prod')->fields([ 
  //     'type' => $entity->getEntityTypeId(),
  //     'uuid' => $entity->uuid->value,
  //     'entity_id_prod' => $entity_id,
  //     ])->execute();
  // }
}

function fetch_mapping($entity) {
  // $connection = Database::getConnection() ;
  // $query = $connection->select('publish_to_prod', 'n');
  // $query->condition('n.uuid', $entity->uuid->value);
  // $query->fields('n', ['entity_id_prod']);
  // $id = $query->execute()->fetchField();
  // return $id;
}
